import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeContextProvider } from '@/lib/ThemeContext'
import ThemeProvider from '@/lib/ThemeProvider'
import AuthProvider from '@/SessionProvider'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <ThemeContextProvider>
        <ThemeProvider>
        <Navbar />
        {children}  
        </ThemeProvider>
        <Footer />      
       </ThemeContextProvider>
        </AuthProvider>
        </body>
    </html>
  )
}
